<?php 
$rq = Zend_Controller_Front::getInstance()->getRequest();
$modul = $rq->getModuleName();
$controller = $rq->getControllerName();
$action = $rq->getActionName();

if (!Zend_Registry::isRegistered('pageTitel')) { // empty($this->pageTitel)) {
    $pageTitel = ($modul !== 'default') ? ucfirst($modul).' ' : '';
    if ($controller !== 'index') $pageTitel.= ucfirst($controller) . ' ';
    if ($action !== 'index') $pageTitel.= ucfirst($action) . ' ';
} else {
    $pageTitel = Zend_Registry::get('pageTitel');
}
$qRrefresh = '20140222';
$hdBgColor = (APPLICATION_ENV === 'production') ? 'inherit' : '#b5f7a1';

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <title><?php if ($pageTitel) echo $pageTitel.'-'; ?>UI-Tourenplaner</title>
    <base href="<?php echo $this->baseUrl(); ?>" />
    <script>var APP_BASE_URL = <?php echo json_encode( $this->baseUrl() ); ?>;</script>
    <script>var droplinemenu_imgPath = <?php echo json_encode( $this->baseUrl() ); ?> + '/css/';
    //alert(droplinemenu_imgPath);
    </script>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<?php if ($use_minified = 1): ?>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/all-layout.min.css?r=<?php echo $qRrefresh; ?>" />
<?php else: ?> 
    <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/jquery/themes/redmond/jquery-ui-1.8.16.custom.css?r=<?php echo $qRrefresh; ?>" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/jquery/ui/layout/css/documentation.css?r=<?php echo $qRrefresh; ?>" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/default.css?r=<?php echo $qRrefresh; ?>" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/jq_themes.extensions.css?r=<?php echo $qRrefresh; ?>" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/jquery/autocomplete_chooser/chooser.css?r=<?php echo $qRrefresh; ?>" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/jquery.fbMultiSearchBox.css?r=<?php echo $qRrefresh; ?>" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/forms.css?r=<?php echo $qRrefresh; ?>" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/jquery/ui/layout/css/global.css" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/css/droplinebar.css?r=<?php echo $qRrefresh; ?>" />
<?php endif; ?>
    <!--[if lte IE 7]> <style type="text/css"> body { font-size: 85%; } </style> <![endif]-->
    <script src="<?php echo $this->baseUrl(); ?>/jquery/jquery-1.5.1.js?r=<?php echo $qRrefresh; ?>"></script><!-- 1.5.1.js 1.7.2.min.js 1.8.3.js></script  -->
    <script src="<?php echo $this->baseUrl(); ?>/jquery/jquery-ui-1.8.12.js?r=<?php echo $qRrefresh; ?>"></script><!-- ui/minified/jquery-ui.min.js jquery-ui-1.9.2.min.js -->
    <script src="<?php echo $this->baseUrl(); ?>/jquery/ui/i18n/jquery.ui.datepicker-de.js?r=<?php echo $qRrefresh; ?>"></script><!-- ui/minified/jquery-ui.min.js jquery-ui-1.9.2.min.js -->
    
    <!-- jquery-plugin ui.layout: 
     * Docs: http://layout.jquery-dev.net/documentation.html
     * Tips: http://layout.jquery-dev.net/tips.html
     * Help: http://groups.google.com/group/jquery-ui-layout -->
    
    <script src="<?php echo $this->baseUrl(); ?>/jquery/ui/layout/jquery.layout-latest.js?r=<?php echo $qRrefresh; ?>" type="text/javascript "></script>
    <script src="<?php echo $this->baseUrl(); ?>/jquery/js_init/init_layout.js?r=<?php echo $qRrefresh; ?>" type="text/javascript "></script>

    <?php echo $this->headTitle(); ?>
    <?php echo $this->jQuery() . PHP_EOL; ?>
    <?php 
        JqGridHeader::enable(true);
        echo JqGridHeader::getLocal(array('without' => array('cssTheme','cssMulti','jQuery','jQueryUI','jQueryMulti')));  ?>
    
    <?php echo $this->headScript (); ?>
    <?php echo $this->headStyle();  ?>
    
    <?php 
    if ($use_minified = 1) { ?>  
    <script src="<?php echo $this->baseUrl(); ?>/jquery/util/min/jquery.util-all.min.js?r=<?php echo $qRrefresh; ?>" type="text/javascript"></script>
    <?php } else { ?>
    <script src="<?php echo $this->baseUrl(); ?>/jquery/util/Fb.core.js?r=<?php echo $qRrefresh; ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl(); ?>/jquery/util/droplinemenu.js?r=<?php echo $qRrefresh; ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl(); ?>/jquery/util/jquery.chooser.js?r=<?php echo $qRrefresh; ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl(); ?>/jquery/util/jquery.fbChooser.js?r=<?php echo $qRrefresh; ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl(); ?>/jquery/util/jquery.fbIcon.js?r=<?php echo $qRrefresh; ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl(); ?>/jquery/util/jquery.plugin.cookie.js?r=<?php echo $qRrefresh; ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl(); ?>/jquery/util/jquery.fbMultiSearchBox.js?r=<?php echo $qRrefresh; ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl(); ?>/jquery/util/jquery.ui.combobox.js?r=<?php echo $qRrefresh; ?>" type="text/javascript"></script>
    <script src="<?php echo $this->baseUrl(); ?>/jquery/waypoints/waypoints.js?r=<?php echo $qRrefresh; ?>" type="text/javascript"></script>
<?php } ?>
<?php if (isset($this->sidebar) && $this->sidebar['openOnload']) { ?>
<script>$(function() { if (pageLayout) pageLayout.open( "west" ); });</script>
<?php } ?>
</head>

<body class="env-<?= APPLICATION_ENV ?>">
<DIV class="ui-layout-north xui-widget-header" style="padding-top:8px;background-color:<?= $hdBgColor; ?>">
        <?php echo $this->render('header.phtml') ?>        
</DIV>

<DIV class="ui-layout-center content">

    <H1 id="top"><?php if ($pageTitel) echo $pageTitel; ?></H1>
    
    <div id="content"><?php echo $this->layout()->content ?></div>
        <?php echo $this->render('footer.phtml') ?>
        <?php if (0) echo $this->action('index', 'dbprofiler'); ?>
</DIV>
    
<DIV id="xLayoutWest" class="ui-layout-west" style="display: none;height:100%">
    <?php echo $this->layout()->sidebar ?>
</DIV>
</body>
</html>